name: Daily Weather Alert

on:
  schedule:
    # This runs at 08:00 UTC (4:00 AM Brooklyn time) every day
    - cron: '0 8 * * *'
  workflow_dispatch: # This allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          # Add any other API keys you used here
        run: python main.py
